name: Echo Changed Files

on:
  push:
    branches: [ Kenebehi-workflow ]

jobs:
  echo-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Changed Files
        id: get-changed-files
        run: |
          message=$(git diff --name-only -r HEAD^1 HEAD )
          message=$(echo $message | tr '\n' ' ')
          echo "EDITED_FILES=$message" >> "$GITHUB_OUTPUT"
      - name: Get color
        run: echo "The selected files is ${{ steps.get-changed-files.outputs.EDITED_FILES }}"


      # - name: 
      #   id: 
      #   run: |
      #     edited_files = $(git diff --name-only -r HEAD^1 HEAD)
      #     echo "EDITED_FILES=edited_files" >> "$GITHUB_OUTPUT"

      # - name: Do Something with Changed Files
      #   run: |
      #     echo "The selected files is ${{ steps.get-changed-files.outputs.EDITED_FILES }}"

