name: Echo Changed Files

on:
  push:
    branches: [ Kenebehi-workflow ]

jobs:
  echo-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files in the dags folder
        id: tests
        run: |
          git diff --name-only -r HEAD^1 HEAD 

      - name: Get Changed Files
        id: get-changed-files
        run: |
          echo $(git diff --name-only -r HEAD^1 HEAD) >> "$GITHUB_ENV"

      - name: Do Something with Changed Files
        run: |
          echo "${{ env.action_state }}"
