name: Echo Changed Files

on:
  push:
    branches: [ Kenebehi-workflow ]

jobs:
  echo-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Changed Files
        id: get-changed-files
        run: |
          message=$(git diff --name-only -r HEAD^1 HEAD )
          message=$(echo $message | tr '\n' ' ')
          echo "EDITED_FILES=$message" >> "$GITHUB_OUTPUT"

      - name: Get Deleted Files
        id: get-changed-files
        run: |
          message=$(git diff --diff-filter=D --name-only HEAD^ HEAD )
          message=$(echo $message | tr '\n' ' ')
          echo "DELETED_FILES=$message" >> "$GITHUB_OUTPUT"


      - name: Get Files
        run: |
          SERVICES="${{ steps.get-changed-files.outputs.EDITED_FILES }}"
          FILES="$(echo $SERVICES | tr ' ' '\n' | grep "services/.*\.py" | awk -F/ '{print $NF}' | tr '\n' ' ')"
          echo $FILES

          INCLUDES=""
          for path in $FILES; do
              INCLUDES="$INCLUDES --include $path"
          done
          echo "$INCLUDES"

      #     aws s3 sync ./workers s3://your-bucket-name --exclude "*" $INCLUDES