name: Echo Changed Files

on:
  push:
    branches: [ Kenebehi-workflow ]

jobs:
  echo-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files in the dags folder
        id: tests
        run: |
          git diff --name-only -r HEAD^1 HEAD 
      - name: Set color
        id: random-color-generator
        run: echo "EDITED_FILES=$(git diff --name-only -r HEAD^1 HEAD )" >> "$GITHUB_OUTPUT"
      - name: Get color

        run: echo "The selected color is ${{ steps.random-color-generator.outputs.EDITED_FILES }}"


      # - name: Get Changed Files
      #   id: get-changed-files
      #   run: |
      #     edited_files = $(git diff --name-only -r HEAD^1 HEAD)
      #     echo "EDITED_FILES=edited_files" >> "$GITHUB_OUTPUT"

      # - name: Do Something with Changed Files
      #   run: |
      #     echo "The selected files is ${{ steps.get-changed-files.outputs.EDITED_FILES }}"

