name: Echo Changed Files

on:
  push:
    branches: [ Kenebehi-workflow ]

jobs:
  echo-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files in the dags folder
        id: tests
        run: |
          git diff --name-only -r HEAD^1 HEAD 

      - name: Get Changed Files
        id: get-changed-files
        run: |
          changed_files=$(git diff --name-only -r HEAD^1 HEAD)
          echo "::set-output name=changed_files::$changed_files"
          echo "name=changed_files" >> $GITHUB_OUTPUT

      - name: Do Something with Changed Files
        run: |
          files=$1
          # Do something with the changed files
          echo "${{ steps.get-changed-files.changed_files }}"
          echo $GITHUB_OUTPUT
