name: Echo Changed Files

on:
  push:
    branches: [ Kenebehi-workflow ]

jobs:
  echo-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get changed files for Airflow Staging DAGs
        id: changed-dags-files
        uses: tj-actions/changed-files@v35
        with:
          base_sha: "${{ github.event.workflow_run.head_sha }}"
          files: |
            airflow/staging/**

      # Re-sync from master to s3 affected by this PR.
      - name: Re-sync affected DAGs
        run: |
          echo "${{ steps.changed-dags-files.outputs.all_changed_and_modified_files }}"
          for file in ${{ steps.changed-dags-files.outputs.all_changed_and_modified_files }}; do
            echo 'aws s3 sync --delete airflow/dags/ s3://xxx/dags/staging/ --exclude "*" --include "**$(basename $file)"'
          done