name: Echo Changed Files

on:
  push:
    branches: [ Kenebehi-workflow ]

jobs:
  echo-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changed files
        run: |
          echo "Changed files:"
          git diff --name-only HEAD^ HEAD | while read file; do realpath "$file"; done
