name: Sync to S3

on:
  push:
    branches:
      - Kenebehi-workflow

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch changed files
        id: fetch-changed-files
        uses: juliangruber/git-changed-files@v1.x
        with:
          format: json
          ref: ${{ github.sha }}

      - name: Authenticate with Vault
        uses: hashicorp/vault-action@v2
        with:
          method: approle
          path: path/to/vault/secret
          role_id: ${{ secrets.VAULT_ROLE_ID }}
          secret_id: ${{ secrets.VAULT_SECRET_ID }}

      - name: Sync files to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --exclude "*" --include-from=- --delete
          env:
            AWS_S3_BUCKET: my-bucket
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: us-east-1
            AWS_S3_ENDPOINT: s3.amazonaws.com
            AWS_S3_ACL: private
            SOURCE_DIR: .
            INCLUDE_REGEX: ${{ steps.fetch-changed-files.outputs.files }}
          run: echo "${{ steps.fetch-changed-files.outputs.files }}" | tr -d '[],' > /tmp/include.txt