name: Echo Changed Files

on:
  push:
    branches: [ Kenebehi-workflow ]

jobs:
  echo-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changed files
        run: |
          echo "Changed files:"
          if git rev-parse --verify HEAD >/dev/null 2>&1; then
            git diff --name-only HEAD^ HEAD
          else
            git ls-tree --name-only -r HEAD
          fi | while read file; do realpath "$file"; done
