name: Master build

# raise pr -> runs pr-checks.yml
# merge with master -> runs master-build.yml
### release -> |
#      runs sync-s3-dags.yaml
#
#
#
#
# manual intervention
### on workflow_dispatch -> runs sync-s3-dags-[staging/manually].yaml

## https://vault.secrets.hellofresh.io/v1/automation/dwh-cluster-automation/googleapi_gsheet

# on push 0a62ca4c61399c74adb267bb5fda9ef0bd9ed6ee

concurrency: Master build

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - "ken"

jobs:
  docker-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      # import secrets
      # checkout helper scripts hellofresh/jetstream-ci-scripts
      # bump version
      # build docker
      # github release
      # get aws details
      # sync dq files
      
      - name: release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create v1.0.1 --title test --generate-notes

        # - name: Get changed Airflow  DAG's
        #   id: updated-dags-files
        #   uses: tj-actions/changed-files@v35
        #   with:
        #     base_sha: "${{ steps.store_value.outputs.myOutput }}"
        #     files: |
        #       airflow/dags/**
          
        # - name: print changed files
        #   run: |
        #     echo "${{ steps.updated-dags-files.outputs.all_changed_and_modified_files }}"