---
name: Echo Changed Files

on:
    release:
        types:
        - published

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
          with:
            ref: ${{ github.event.pull_request.head.sha }}
            
        - name: Print commit SHA
          run: |
            echo "Commit SHA: ${{ github.event.pull_request.head.sha }}"
    
 