---

  name: 'Sync S3 DAGs and settings'
  
  on:
    release:
      types:
        - published
  
  jobs:
    sync-dags:
      name: Copy DAGs to S3
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v3

        - name: Print event payload
          run: echo "${{ github.event.release.head.sha }}"

        - name: Print event payload
          id: vars
          run: echo "sha_short=$(git rev-parse --short HEAD^)" >> $GITHUB_OUTPUT

        - name: Print event payload
          run: echo "{{ steps.vars.outputs.sha_short }}"
