---

  name: 'Sync S3 DAGs and settings'
  
  on:
    release:
      types:
        - published
  
  jobs:
    sync-dags:
      name: Copy DAGs to S3
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v3

        - name: Debug output
          run: |
            echo "Current branch: $(git branch --show-current)"
            echo "Latest commit: $(git rev-parse HEAD)"
            echo "Previous commit: $(git rev-parse HEAD^)"
            echo "Release target commitish: ${{ github.event.release.target_commitish }}"
        
        - name: Print event 
          run: echo "$(git rev-parse main~1)"


        - name: Get previous tag name
          id: get_previous_tag
          run: echo "::set-output name=tag_name::$(git describe --abbrev=0 --tags ${{ github.event.release.tag_name }}^)"
    
        - name: Get commit SHAs
          id: get_commit_shas
          run: |
            PREVIOUS_TAG=$({{ steps.get_previous_tag.outputs.tag_name }})
            COMMIT_SHAS=$(git log --pretty=%H $PREVIOUS_TAG..${{ github.event.release.tag_name }})
            echo "Commit SHAs: $COMMIT_SHAS"
          


