---

  name: 'Sync S3 DAGs and settings'
  
  on:
    release:
      types:
        - created
  
  jobs:
    sync-dags:
      name: Copy DAGs to S3
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v3
          with:
            fetch-depth: 0

        - name: Get merge branch sha
          id: merge-branch-sha
          run: |
            git rev-parse HEAD
  
        - name: Get master release branch sha
          id: master-release-sha
          run: |
              git rev-parse refs/heads/master    

        - name: Print SHA_ID
          run: |
            echo "merge branch sha ${{ steps.merge-branch-sha.outputs.id }}"
            echo "master release sha ${{ steps.master-release-sha.outputs.id }}"

        # - name: Get changed Airflow  DAG's
        #   id: updated-dags-files
        #   uses: tj-actions/changed-files@v35
        #   with:
        #     base_sha: "${{ steps.store_value.outputs.myOutput }}"
        #     files: |
        #       airflow/dags/**
          
        # - name: print changed files
        #   run: |
        #     echo "${{ steps.updated-dags-files.outputs.all_changed_and_modified_files }}"


