name: Get Merge Commit SHA


on:
  push:
    branches:
      - main
      
jobs:
  get_sha:
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Pull Request
        id: pr
        run: |
          response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?state=open&base=main" \
            | jq -r '.[0]')
          echo "::set-output name=number::$(echo $response | jq -r '.number')"
          echo "::set-output name=merge_commit_sha::$(echo $response | jq -r '.merge_commit_sha')"
      - name: Print Merge Commit SHA
        run: |
          echo "Merge Commit SHA: ${{ steps.pr.outputs.merge_commit_sha }}"
