---

  name: 'Sync S3 DAGs and settings'
  
  on:
    release:
      types:
        - published
  
  jobs:
    sync-dags:
      name: Copy DAGs to S3
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v3
          with:
            fetch-depth: 2

        - name: Debug output
          run: |
            echo "Current branch: $(git branch --show-current)"
            echo "Release target commitish: ${{ github.event.release.target_commitish }}"
        
        - name: Print event 
          run: echo "$(git rev-list -n 1 $(git tag --sort=-creatordate | sed -n '2p'))"
          


