---

  name: 'Sync S3 DAGs and settings'
  
  on:
    release:
      types:
        - created
  
  jobs:
    sync-dags:
      name: Copy DAGs to S3
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v3
          with:
            fetch-depth: 0

        - name: Get merge branch sha
          id: merge-branch-sha
          run: |
            git rev-parse HEAD^
  

        - name: Print SHA_ID
          run: |
            echo "merge branch sha ${{ steps.merge-branch-sha.outputs.id }}"




